apiVersion: v1
kind: Service
metadata:
  name: votingapp-service
  labels:
    app: votingapp-service
spec:
  selector:
    app: votingapp-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer